### ISSUE TITLE
missing error when external dependency unavailable

### ISSUE THREAD

**Issue by DasFaultier** [SLUB-digitalpreservation/checkit_tiff_plugin4rosetta#1]
Recent events have shown that the plugin will not return any errors if exiftool cannot be found in the configured path. Instead, the plugin will just return "valid" for the file that was checked. No metadata are extracted.
I suggest adding checks to make sure all external programs are available. If one of the external resources is unavailable, the plugin needs to return "invalid", accompanied by an error message describing the exact nature of the problem.

**Comment by ghost** [comment]
Fixed in https://github.com/SLUB-digitalpreservation/checkit_tiff_plugin4rosetta/commit/7c384198081e3a9478a84e147f20f10af3f02013
